### ISSUE TITLE
Potential DOS vuln using symbols as hash keys

### ISSUE THREAD

**Issue by jneen** [haileys/toml2#1]
Hey there!  This is awesome!

I just wanted to mention that the symbol table is never garbage collected, so interning potentially malicious data (i.e. arbitrary keys in TOML documents) could cause Ruby to guzzle memory and never give it back.  I believe this is the reason the JSON and YAML parsers continue to use strings as hash keys, because the garbage collector will free them eventually (more docs on this forthcoming...).

**Comment by haileys** [comment]
Hey, thanks for the concern.

Unfortunately symbolizing keys is an unavoidable consequence of toml2's parsing technique, so there's not a whole lot I can do to keep them as strings.

**Comment by jneen** [comment]
Yeah, just noticed the massive evalled string..... this is the least of the security issues :)
